config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :articles do
    resources :comments
  end
  root 'simple_pages#index'
  get 'about', to: 'simple_pages#about'
  get 'contact', to: 'simple_pages#contact'
  resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    can :manage, User, id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article

  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_url, alert: exception.message
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
    @articles = Article.paginate(:page => params[:page])
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @comments = @article.comments.order("created_at DESC")
    @comments = @article.comments.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :description, :content, :image_url)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @article, notice: 'Review was created successfully.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { redirect_to @article, alert: 'Review was not saved successfully.' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:user_id, :body)
  end

end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController

  def index
    @articles = Article.all.order("created_at DESC")
  end

  def contact
    @articles = Article.order("created_at DESC").limit(3)
  end

  def about
    @articles = Article.order("created_at DESC").limit(3)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_comments.html.erb
<div class="article-reviews">
  <% @comments.each do |comment| %>
  <div class="row">
    <hr>
    <p><%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small></p>
    <p><%= comment.body %></p>
  </div>
  <% end %>
  <%= will_paginate @comments %>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/_new_comment.html.erb
<div class="add-comment">
  <% if signed_in? %>
  <h4>Add a review:</h4>
  <%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :body, "Comments" %><br>
    <%= f.text_area :body, class: "text_area" %>
  </p>
  <p>
    <%= f.submit "Submit", class: "btm-sbt" %>
  </p>
  <% end %>
  <% end %>
</div>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article, :class => "show" %> |
<%= link_to 'Back', articles_path, :class => "back" %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th class="image-text">Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= image_tag(article.image_url, class: "img-fluid box") unless article.image_url.nil? %></td>
        <td><%= link_to 'Show', article, :class => "edit-product"%></td>
        <td><%= link_to 'Edit', edit_article_path(article), :class => "edit-product"%></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }, :class => "edit-product"%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @articles %>
<br>

<%= link_to 'New Article', new_article_path, :class => "new" %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path, :class => "back" %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid show-page">
  <div class= "image"><%= image_tag(@article.image_url, class: "img-fluid") unless @article.image_url.nil? %></div>
  <h2><%= @article.title %></h2>
  <h6><%= @article.description %></h6>
  <p><%= @article.content %></p>
  <%= render 'new_comment' %>
</div>
<%= render 'comments' %>


<%= link_to 'Edit', edit_article_path(@article), :class => "show" %> |
<%= link_to 'Back', articles_path, :class => "back" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Blog</title>

  <link href="https://fonts.googleapis.com/css?family=Noto+Serif+JP:200,300,400,500,700" rel="stylesheet">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="nav">
    <div class="nav-header">
      <div class="nav-title">
        <%= link_to 'Blog Cf', root_path, :class => "navbar-brand" %>
      </div>
    </div>
    <div class="nav-btn">
      <label for="nav-check">
        <span></span>
        <span></span>
        <span></span>
      </label>
    </div>
    <input type="checkbox" id="nav-check">
    <div class="nav-links ml-auto">
      <%= link_to 'Home', root_path, :class => "home" %>
      <%= link_to 'About', about_path %>
      <%= link_to 'Contact', contact_path %>
      <%= link_to 'Articles', articles_path %>
      <%= link_to 'New', new_article_path %>
      <% if user_signed_in? %>
      <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %>
      <% else %>
      <%= link_to('Login', new_user_session_path, class: "nav-link") %>
      <% end %>
    </div>
  </div>


  <%= yield %>

  <footer class="container-fluid">
    &copy; 2018 Cf Blog
  </footer>
</body>
</html>

app/views/shared/_sidebar.html.erb
<div class="sidenav">
  <!-- Search form -->
  <input class="form-control" type="text" placeholder="Search" aria-label="Search">
  <div class="latest-posts">
    <h6>Latest Posts</h6>
    <ul>
    <% @articles.each do |article| %>
      <li><%= link_to article.title, article_path(article), class: "post" %></li><br/>
    <% end %>
  </div>
</div>

app/views/simple_pages/about.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-9">
      <h1>About</h1>
      <p class="about">Blog Cf publishes articles on a twice-weekly basis, covering a variety of digital specialisms, <br/>from content and social media marketing, to search and analytics.</p>
    </div>
    <div class="col-xs-12 col-md-3">
      <%= render 'shared/sidebar' %>
    </div>
  </div>
</div>

app/views/simple_pages/contact.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-9">
      <h1>Contact Us</h1>
      <h3 class="address address-top">Address</h3>
      <p class="address">30 Winders Road, SW11 3HB London, UK</p>
      <h3 class="address">Phone number</h3>
      <p class="address">+44 (30) 26050</p>
      <h3 class="address">Email</h3>
      <p class="address add-p">info@blog-cf.co.uk</p>
    </div>
    <div class="col-xs-12 col-md-3">
      <%= render 'shared/sidebar' %>
    </div>
  </div>
</div>

app/views/simple_pages/index.html.erb
<div class="jumbotron">
  <p id="notice"><%= notice %></p>
  <h1 class="display-3">Blog Cf</h1>
  <hr class="my-4">
  <p class = "jumbotron-text">Stay tuned new post coming soon!</p>
  <p class="text-center"><a class="btn btn-primary btn-lg align-center mt-3" href="#" role="button">Sign Up</a></p>
</div>

<div class="container">
  <div class="row">
    <% @articles.each do |article| %>
      <div class="col-xs-12 col-md-4 box-homepage">
        <%= image_tag(article.image_url, class: "img-fluid") unless article.image_url.nil? %>
        <h6><%= link_to article.title, article_path(article) %></h6>
        <p><%= article.description %></p>
        <hr class="my-6">
        <p><%= article.created_at%></p>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>